languageCode = "cn"
languageName = "Chinese"
displayName = "ğŸ‡¨ğŸ‡³ä¸­æ–‡"
isoCode = "cn"
weight = 2
rtl = false

title = "Awesome ChatGPT API"
description = "Awesome ChatGPT API æ˜¯ä¸€ä¸ªä½¿ç”¨ ChatGPT API çš„åº”ç”¨ç¨‹åºå’Œå·¥å…·çš„é›†åˆã€‚"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params]
  # mainSections = ["section1", "section2"]

[author]
  name = "Reorx"
